### ISSUE TITLE
Partial probability keys in reverse order, single measurement does not output partial probability.

### ISSUE THREAD

**Issue by fasihere** [indian-institute-of-science-qc/test_repo#11]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**:
- **Operating system**:

#### What is the current behavior?
1. The partial probability keys are in reverse order of the keys of ensemble probabilities. This inconsistency results in confusions for the user when using the respective dictionaries.
2. Single measurements do not output partial_probability in the result. Currently there is no direct way to get probabilities of a single measurement on specific qubit.

I wanted to know whether these are intended behaviours.

**Comment by biplab37** [comment]
1. I checked it but found both the keys in partial probabilities as well as in ensemble probabilities to be the same. Can you provide more details about what you did?
2. Yes, you are correct. I guess we missed it. One can always find the probabilities from the density matrix but probability output for single qubit measurement should be added. We will try to add this feature in the future. Thanks for pointing it out!

**Comment by fasihere** [comment]
1. 'Reversal of keys' could be a but misleading. I will demonstrate the issue I meant to raise using an example. 

Suppose in a 2 qubit circuit, let ensemble probabilities =  {'00':0, '01':1, '10':0, '11':0} . Then the partial probabilities(measuring both qubits) would be {'00':0, '01':0, '10':1, '11':0}

```python
from qiskit import QuantumCircuit, BasicAer, execute
qc = QuantumCircuit(3,3)
qc.x(2)
for i in range(3):
    qc.measure(i,i)
backend = BasicAer.get_backend('dm_simulator')
run = execute(qc,backend)
result = run.result()
answer = result['results'][0]['data']['partial_probability']
print('Partial probability =',answer)
```
Partial probability =  {'000': 0.0, '100': 1.0, '010': 0.0, '110': 0.0, '001': 0.0, '101': 0.0, '011': 0.0, '111': 0.0}
```python
from qiskit import QuantumCircuit, BasicAer, execute
qc = QuantumCircuit(3,3)
qc.x(2)
qc.measure(0,0, basis='Ensemble')
backend = BasicAer.get_backend('dm_simulator')
run = execute(qc,backend)
result = run.result()
answer = result['results'][0]['data']['ensemble_probability']
print('Ensemble probability =',answer)
```
Ensemble probability = {'000': 0.0, '001': 1.0, '010': 0.0, '011': 0.0, '100': 0.0, '101': 0.0, '110': 0.0, '111': 0.0}

**Comment by biplab37** [comment]
Okay, thanks for the details. This indeed could be confusing to user. Based on the output above the keys for ensemble probability seems more natural convention. So I will change the keys for the partial probabilites.
