### ISSUE TITLE
 Regarding decoherence_and_amp_decay 

### ISSUE THREAD

**Issue by gitkarma** [indian-institute-of-science-qc/test_repo#6]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
In dm_simulator.py 
The amplitude decay ,thermalization and decoherence is applied at end of every clock cycle to all the qubits.
In the main code at line 1173 a for loop is applied for adding errors to all the qubits by calling _add_decoherence_and_amp_decay function .
Inside the function _add_decoherence_and_amp_decay again a for loop is applied for all the qubits at line 411.
I think one of the loop is redundant but not sure .
Request your comments on the same

**Comment by biplab37** [comment]
@gitkarma Thanks for pointing it out. It seems like there have been a mistake. I will look into it carefully, maybe discuss with the other developers and fix this issue soon.
