### ISSUE TITLE
Regarding Bell basis measurement 

### ISSUE THREAD

**Issue by gitkarma** [indian-institute-of-science-qc/test_repo#7]
Currently for Bell basis measurement dm_simulator uses measure method like  qc.measure(0,0,basis='Bell',add_param='23')
Where 'add_param' tells the pair of qubit's on which measurement is being made.
First two arguments are not consider at all and are considered as dummy.
First two args of measure method are only used in case of single qubit measurement.

so if we go with qc.draw(), visually the circuit shows that measurement is being made on 0th qubit and result is stored on 0th classical bit. But in actual the measurement is made on qubit pair '23' in Bell basis

Is it possible to  have  measure method  which will consider the first two parameters (two qubits & classical bits) 
and perform bell basis measurement on those, instead of qubits in 'add_params' argument.
e.g qc.measure([2,3], [0,0] , basis='Bell' )
and qc.draw() gives correct visualization with respect to measurement.

Request you to share your thoughts whether it is advisable/rational  to do it or not.
If its possible, request you to please guide us on how it can be achieved.

**Comment by biplab37** [comment]
As far as I can remember, the `Measure` class in qiskit (see this [file](https://github.com/indian-institute-of-science-qc/qiskit-aakash/blob/09ac4b66f6f8cea09ac82f17bf8dd38ab6fb983e/qiskit/circuit/measure.py)) are written such a way that it can handle only one qubit measurements. Although it is not impossible to do, it required changing a few files. And we wanted to include our simulator by changing the least amount of original qiskit code. We did try to find a way but could not find a simple solution(there might be. you are very welcome to try and inform us) so included the extra information in the `add_param` variable.

Right now if you want to use the `draw` functionality then you can write 
```python
qc.measure([2,3],[2,3],basis="Bell",add_param='23')
```
which will give both the correct result as well as the correct diagram. Note that the first two arguments are not used in the calculation of density matrix.

##### Possible ways to change this
If there is a simple solution to use the first two arguments we will happy to include this in the code. If you are interested in finding such implementation, then you can start with this [file](https://github.com/indian-institute-of-science-qc/qiskit-aakash/blob/09ac4b66f6f8cea09ac82f17bf8dd38ab6fb983e/qiskit/circuit/measure.py) and this [line in the `dm_silumator` code](https://github.com/indian-institute-of-science-qc/qiskit-aakash/blob/09ac4b66f6f8cea09ac82f17bf8dd38ab6fb983e/qiskit/providers/basicaer/dm_simulator.py#L1094).

**Comment by biplab37** [comment]
I am closing this issue for now. If someone wants to change the code(or suggest a way to implement) to incorporate this feature this issue will be reopened or he/she can create a pull request.
